backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://netlify-cms-react-starter.netlify.com # This url will display in the top-right of the CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "locations"
    label: "Location"
    delete: false
    editor:
      preview: false
    folder: content/locations
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Website", name: "website", widget: "string", required: false }
      - { label: "Opening Hours", name: "openingHours", widget: "number", required: false }      
        